name: Github-Contribution-Grid-Snake

on:
  schedule:
    - cron: "0 0 * * *" # 每天 00:00 UTC 自动运行一次
  workflow_dispatch: # 允许手动触发

jobs:
  generate:
    runs-on: ubuntu-latest
    name: generate-github-contribution-snake

    steps:
      # 克隆当前仓库内容
      - name: Checkout repository
        uses: actions/checkout@v3

      # 生成 Snake 动画，输出到指定文件夹
      - name: Generate Snake Game from GitHub Contribution Grid
        uses: Platane/snk@v3
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            assets/snake/github-contribution-grid-snake.svg
            assets/snake/github-contribution-grid-snake.gif

      # 提交更改并推送回当前分支
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add assets/snake
          git commit -m "chore: update snake contribution animation"
          git push
